#!/usr/bin/env python3
import sys

key = [5, 1, 1, 1, 4]
val = [1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1]

uc = []
for line in sys.stdin:
    line = line.rstrip().split()
    if line[0] == '#':
        continue
    uc.append(line)

uc_dict = [0] * (2 ** sum(key))
for line in uc:
    klen = len(key)
    value = 0
    for i, l in enumerate(val):
        v = 0 if line[i + klen] == 'x' else int(line[i + klen], 16)
        value = (value << l) | v
    keylist = [0]
    for i, l in enumerate(key):
        if line[i] == 'x':
            o = len(keylist)
            keylist = keylist * (2 ** l)
            for j in range(2 ** l):
                for m in range(o):
                    keylist[j * o + m] = (keylist[j * o + m] << l) | j
        else:
            v = int(line[i], 16)
            keylist = [((k << l) | v) for k in keylist]
    for s in keylist:
        uc_dict[s] = value

uc_dict += [0] * (8192 - len(uc_dict))
with open("ucode.01", "w+") as f:
    for i in uc_dict:
        print(format(i >> 8, 'x'), file=f)

with open("ucode.02", "w+") as f:
    for i in uc_dict:
        print(format(i & 0xff, 'x'), file=f)
