#!/usr/bin/env python3
import sys

key = [5, 1, 1, 1, 4]
val = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

uc = []
for line in sys.stdin:
    line = line.rstrip().split()
    if line[0] == '#':
        continue
    uc.append(line)

uc_dict = [0] * (2 ** sum(key))
for line in uc:
    klen = len(key)
    value = 0
    for i, l in enumerate(val):
        v = 0 if line[i + klen] == 'x' else int(line[i + klen], 16)
        vv = 0
        for m in range(l):
            vv = (vv << m) | ((v >> m) & 1)
        value = (value << l) | vv
    mask = [0] * sum(key)
    acc = 0
    for i, l in enumerate(key):
        if line[i] == 'x':
            for o in range(l):
                mask[o + acc] = -1
        else:
            n = int(line[i], 16)
            for o in range(l):
                mask[o + acc] = (n >> o) & 1
        acc += l
    for i in range(2 ** sum(key)):
        match = True
        for m in range(sum(key)):
            if mask[m] == -1:
                continue
            if mask[m] != ((i >> m) & 1):
                match = False
                break
        if match:
            uc_dict[i] = value

uc_dict += [0] * (8192 - len(uc_dict))
with open("ucode.01", "w+") as f:
    for i in uc_dict:
        print(format(i >> 8, 'x'), file=f)

with open("ucode.02", "w+") as f:
    for i in uc_dict:
        print(format(i & 0xff, 'x'), file=f)
